name: zegen_test_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  carousel_slider: ^5.1.1
  connectivity_plus: ^7.0.0
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.12.0
  get: ^4.7.3
  http: ^1.6.0
  shared_preferences: ^2.5.4
  toastification: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/sf-pro-display/SFPRODISPLAYREGULAR.OTF
          weight: 400
        - asset: assets/fonts/sf-pro-display/SFPRODISPLAYMEDIUM.OTF
          weight: 500
        - asset: assets/fonts/sf-pro-display/SFPRODISPLAYSEMIBOLDITALIC.OTF
          weight: 600
          style: italic
        - asset: assets/fonts/sf-pro-display/SFPRODISPLAYBOLD.OTF
          weight: 700